### ISSUE TITLE
Off-chain data unavailable 

### ISSUE THREAD

**Issue by tloriato** [sdec-brasil/worker#7]
The worker is going to fail if off-chain data isn't available right now. 

It should detect that case and insert in the database (we might need another field?) what it has and that it couldn't retrieve more information.

https://github.com/sdec-brasil/worker/blob/71ee2be7b60b2143d6b2eb640313b289675d9bcd/Mce/DataStore.py#L3060

**Comment by FranciscoThiesen** [comment]
Agreed. We do have to adapt to the case where off-chain info is not available for download at the moment.

**Comment by FranciscoThiesen** [comment]
@tloriato 

I am addressing this issue at the partial_receipts branch.

For testing the proposed solution, you should use the partial_receipts branch of the dashboard repo + partial_receipts branch of the docker-multichain repo.
